name: Build

on:
  push:
    tags: "*"

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - build: linux-amd64
            os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-gnu
            archive-name: reader-mini-${{ github.ref_name }}-linux-amd64.tar.gz
          - build: linux-armv8
            os: ubuntu-24.04-arm
            rust: stable
            target: aarch64-unknown-linux-gnu
            archive-name: reader-mini-${{ github.ref_name }}-linux-arm64.tar.gz
          - build: windows
            os: windows-latest
            rust: stable-x86_64-msvc
            target: x86_64-pc-windows-msvc
            archive-name: reader-mini-${{ github.ref_name }}-windows-amd64.7z
    steps:
    - uses: actions/checkout@v6
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        target: ${{ matrix.target }}
    - name: Build
      run: cargo build --verbose --release --target ${{ matrix.target }}
      env:
        RUST_BACKTRACE: 1
    - name: Strip binary (linux and macos)
      if: matrix.build == 'linux-amd64' || matrix.build == 'linux-armv8'
      run: strip "target/${{ matrix.target }}/release/reader-mini"
    - name: Build archive
      shell: bash
      run: |
        mkdir archive
        cp LICENSE README.md archive/
        cd archive
        if [ "${{ matrix.build }}" = "windows" ]; then
          cp "../target/${{ matrix.target }}/release/reader-mini.exe" ./
          7z a "${{ matrix.archive-name }}" LICENSE README.md reader-mini.exe
        else
          cp "../target/${{ matrix.target }}/release/reader-mini" ./
          tar -czf "${{ matrix.archive-name }}" LICENSE README.md reader-mini
        fi
    - name: Release
      uses: softprops/action-gh-release@v3
      with:
        files: archive/${{ matrix.archive-name }}
